### PR TITLE
New bindings: beginning/end of defun, up/down sexp

### PR DESCRIPTION
**Pull request by grammati**
These are things that I used to do frequently when I used paredit,
before switching to spacemacs.

### CODE REVIEW

**Comment by bpstahlman** [comment]
The absence of these functions was one of the things that kept me from considering evil-lisp-state when I started using emacs. Is there a reason the pull request hasn't being accepted? This package seems to have great potential, but I notice there hasn't been much activity in a while. Is evil-lisp-state still under active development?

**Comment by bpstahlman** [comment]
@grammati Do you know what the status of this package is? I haven't seen much activity by the maintainer over the past year, and am having trouble getting any response on my issue submission...

**Comment by grammati** [comment]
@bpstahlman, no, I have no idea. My guess would be that @syl20bnr is so inundated with issues and PRs on spacemacs that he has stopped watching his other repos.

**Comment by bpstahlman** [comment]
Ok. Thanks. I can certainly appreciate that, though I must admit it makes me a bit reluctant to start relying on the package. Unless I'm completely missing the point of the "lisp" state (and it's possible I have), the issue I pointed out in https://github.com/syl20bnr/evil-lisp-state/issues/37 is really significant. In fact, it's hard to imagine it hasn't been noticed before now if many people are using the package. On the other hand, it would be fairly easy to fix, but given the apparent difficulty in getting PR's accepted, I'm not sure whether I would be better off just forking...

**Pull request closed without merging**
